// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniCrmApi.Data;

#nullable disable

namespace MiniCrmApi.Migrations
{
    [DbContext(typeof(MiniCrmContext))]
    [Migration("20251110115720_OrderEntityUpdate")]
    partial class OrderEntityUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniCrmApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Home & Kitchen"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Toys & Games"
                        });
                });

            modelBuilder.Entity("MiniCrmApi.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Customer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Istanbul",
                            City = "Istanbul",
                            Name = "Ali Umur",
                            PhoneNumber = "99999999999"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Istanbul",
                            City = "Istanbul",
                            Name = "Mustafa Asim",
                            PhoneNumber = "88888888888"
                        });
                });

            modelBuilder.Entity("MiniCrmApi.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("MiniCrmApi.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetail", (string)null);
                });

            modelBuilder.Entity("MiniCrmApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "",
                            Name = "Laptop",
                            Price = 10000m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "",
                            Name = "Smartphone",
                            Price = 7000m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "",
                            Name = "Wireless Headphones",
                            Price = 1500m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "",
                            Name = "C# Programming Book",
                            Price = 200m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "",
                            Name = "Design Patterns Book",
                            Price = 180m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "",
                            Name = "Database Systems Book",
                            Price = 220m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "",
                            Name = "T-Shirt",
                            Price = 100m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "",
                            Name = "Jeans",
                            Price = 250m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "",
                            Name = "Jacket",
                            Price = 500m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Description = "",
                            Name = "Coffee Maker",
                            Price = 600m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Description = "",
                            Name = "Microwave Oven",
                            Price = 1200m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Description = "",
                            Name = "Blender",
                            Price = 400m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            Description = "",
                            Name = "Board Game",
                            Price = 300m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Description = "",
                            Name = "Puzzle",
                            Price = 150m,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            Description = "",
                            Name = "RC Car",
                            Price = 800m,
                            StockQuantity = 30
                        });
                });

            modelBuilder.Entity("MiniCrmApi.Models.Order", b =>
                {
                    b.HasOne("MiniCrmApi.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("MiniCrmApi.Models.OrderDetail", b =>
                {
                    b.HasOne("MiniCrmApi.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniCrmApi.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MiniCrmApi.Models.Product", b =>
                {
                    b.HasOne("MiniCrmApi.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniCrmApi.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MiniCrmApi.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MiniCrmApi.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("MiniCrmApi.Models.Product", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
